name:                HaskellHomework
version:             0.1.0.0
github:              "kirillgla/HaskellHomework"
license:             BSD3
author:              "Kirill"
maintainer:          "kirill_gla@mail.ru"
copyright:           "Kirill Glazyrin, 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kirillgla/HaskellHomework#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
    - src
  dependencies:
    - mtl

executables:
  HaskellHomework-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellHomework

tests:
  HaskellHomework-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellHomework
    - tasty
    - tasty-hunit
